[package]
name = "questions"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "questions"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

questions_integrity = { workspace = true } 
